#!/bin/bash

[% c("var/set_default_env") -%]

clone_dir='[% c("basedir") %]/hg_clones/[% project %]'
mkdir -p "$clone_dir"
cd "$clone_dir"
tmpdir=$(mktemp -d)

[% FOREACH lang = c('var/locales') %]
  [% SET lang = tmpl(lang);
     SET hgurl = "https://hg.mozilla.org/l10n-central/" _ lang %]
  if test -d [% lang %]
  then
      cd [% lang %]
      [% c("hg") %] pull [% hgurl %]
  else
      [% c("hg") %] clone [% hgurl %] [% lang %]
      cd [% lang %]
  fi
  hg_hash=$([% c("basedir") %]/projects/firefox-locale-bundle/get_hg_hash \
                $rootdir/[% c('input_files_by_name/firefox_json') %] \
                [% lang %])
  [% c("hg") %] archive -r "$hg_hash" -t files "$tmpdir"/[% lang %]
  cd ..
[% END %]

tar -C "$tmpdir" -czf [% dest_dir %]/[% c("filename") %] .
rm -Rf "$tmpdir"
