#!/bin/bash
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir
tar xf [% c('input_files_by_name/python') %]
cd Python-[% c('version') %]
./configure --prefix=$distdir
make -j[% c("buildconf/num_procs") %]
make prefix=$distdir install
cd /var/tmp/dist
[% c('tar', {
	tar_src => 'python',
	tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
