#!/bin/bash
[% c("var/set_default_env") -%]
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
distdir=/var/tmp/dist/[% project %]
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.bz2
cd /var/tmp/build/[% project %]-[% c('version') %]
# Even if we are not shipping libgmpxx anymore we still need --enable-xcc
# during compile time.
./configure --disable-static --enable-shared --enable-cxx \
    [% c("var/configure_opt") %] [% c("var/configure_opt_gmp") %] --prefix=$distdir
make -j[% c("buildconf/num_procs") %]
make install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
