#!/bin/bash
[% c("var/set_default_env") -%]
distdir="/var/tmp/dist/[% project %]"
[% c("var/set_PTDIR_DOCSDIR") -%]
mkdir -p $PTDIR
mkdir -p /var/tmp/build
unzip -d /var/tmp/build $rootdir/[% project %]-[% c('version') %].zip
cd /var/tmp/build/[% project %]-[% c('version') %]
export PYTHON=python2
$PYTHON setup.py build --build-lib build
cp -a build/zope $PTDIR/
cd $distdir
[% c('tar', {
        tar_src => [ '.' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
