#!/usr/bin/env bash

IBB_START_PROG="$(grep '^X-I2PBrowser-ExecShell' $1 | tail -1 | sed 's/^X-I2PBrowser-ExecShell=//' | sed 's/%.//')"

shift

if [ "$#" -ge 1 ]
then
  echo "Launching '${IBB_START_PROG} $@'..."
else
  echo "Launching '${IBB_START_PROG}'..."
fi

${IBB_START_PROG} "$@"
