#!/bin/bash
[% c("var/set_default_env") -%]
distdir="/var/tmp/dist/[% project %]"
[% IF c("var/windows") -%]
  [% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
[% ELSE -%]
  [% c("var/set_PTDIR_DOCSDIR") -%]
  mkdir -p $PTDIR
[% END -%]
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf $rootdir/PyYAML-[% c('version') %].tar.gz
cd /var/tmp/build/PyYAML-[% c('version') %]
[% IF c("var/windows") -%]
  pydir="$distdir/python"
  mkdir -p $pydir/Lib/site-packages
  export PYTHONPATH="$(wine winepath -w $pydir)\\Lib\\site-packages"
  $PYTHON setup.py install --prefix=$(wine winepath -w $pydir)
[% ELSE -%]
  export PYTHON=python2
  $PYTHON setup.py build --build-lib build
  cp -a build/yaml $PTDIR/
[% END -%]
cd $distdir
[% c('tar', {
        tar_src => [ '.' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
